# **Beginner Level — Superstore Sales Analysis**
---

## **Project Overview**

This project analyzes a retail sales dataset to understand sales performance, profitability, customer segments, product categories, regional performance, and trends over time. 

The objective is to transform raw transactional data into meaningful business insights and present the findings through an Excel-based dashboard.

The analysis follows the workflow:

Raw Data → Data Understanding → Data Cleaning → Exploratory Data Analysis → KPI Analysis → Business Insights → Excel Dashboard

## **Business Objective**

The objective of this analysis is to evaluate the overall sales and profitability performance of the business and identify important patterns across time, product categories, customer segments, and geographic regions.

The analysis will focus on questions such as:

- How much revenue is being generated?
- How profitable is the business?
- Which categories and sub-categories perform best?
- Which regions contribute the most sales and profit?
- How do sales and profit change over time?
- Which products or segments require attention?
- Are there areas where high sales do not translate into high profit?

The final findings will be used to create a business-oriented Excel dashboard and provide actionable recommendations.

## **Data Loading**

The dataset was loaded into a Pandas DataFrame using Python.

Pandas is used because it provides efficient data structures and functions for manipulating, inspecting, cleaning, and analyzing tabular data.

The loaded dataset is stored in the variable `df`, which will be used throughout the analysis.

In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## **Data Inspection**

After loading the dataset, an initial inspection was performed to understand its structure, dimensions, data types, statistical characteristics, missing values, and duplicate records.

The following checks were performed:

- Dataset dimensions using `df.shape`
- Column names and data types using `df.info()`
- Statistical summary using `df.describe()`
- Missing-value detection using `df.isnull().sum()`
- Duplicate-record detection using `df.duplicated().sum()`

### Initial Observations

The dataset contains **10,194 records and 21 columns**.

All columns contain 10,194 non-null values, indicating that there are **no missing values** in the dataset.

The dataset contains:
- 2 datetime columns
- 3 floating-point columns
- 2 integer columns
- 1 object-type column for Postal Code
- 13 string/categorical columns

No duplicate rows were detected using `df.duplicated().sum()`.

The numerical summary also provides an initial understanding of the distribution and range of variables such as Sales, Quantity, Discount, and Profit.

These observations establish the initial quality and structure of the dataset before proceeding to data cleaning and preparation.

In [77]:
df = pd.read_excel("../data/superstore_sales.xls")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [78]:
df.shape

(10194, 21)

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  datetime64[us]
 3   Ship Date       10194 non-null  datetime64[us]
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  str
 6   Customer Name   10194 non-null  str
 7   Segment         10194 non-null  str
 8   Country/Region  10194 non-null  str
 9   City            10194 non-null  str
 10  State/Province  10194 non-null  str
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  str
 13  Product ID      10194 non-null  str
 14  Category        10194 non-null  str
 15  Sub-Category    10194 non-null  str
 16  Product Name    10194 non-null  str
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: datetime64[us](2), float64(3), int64(2), object(1), str(13)
memory usage: 1.6+ MB

In [80]:
df.describe()

,Row ID,Order Date,Ship Date,Sales,Quantity,Discount,Profit
count,10194.000000,10194,10194,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,2025-04-29 11:48:25.002943,2025-05-03 10:52:45.626839,228.225854,3.791838,0.155385,28.673417
min,1.000000,2023-01-03 00:00:00,2023-01-07 00:00:00,0.444000,1.000000,0.000000,-6599.978000
25%,2549.250000,2024-05-14 00:00:00,2024-05-19 00:00:00,17.220000,2.000000,0.000000,1.760800
50%,5097.500000,2025-06-25 00:00:00,2025-06-28 00:00:00,53.910000,3.000000,0.200000,8.690000
75%,7645.750000,2026-05-14 00:00:00,2026-05-18 00:00:00,209.500000,5.000000,0.200000,29.297925
max,10194.000000,2026-12-30 00:00:00,2027-01-05 00:00:00,22638.480000,14.000000,0.800000,8399.976000
std,2942.898656,NaN,NaN,619.906839,2.228317,0.206249,232.465115

In [81]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [82]:
df.duplicated().sum()

np.int64(0)

## **Data Cleaning & Preparation**

Data cleaning is the process of identifying and handling problems in a dataset that may affect the accuracy or reliability of analysis.

Although the initial inspection shows that the dataset contains no missing values or completely duplicated rows, additional validation is required before analysis.

The cleaning process will verify:

- Column names and formatting
- Data types
- Categorical values and unnecessary whitespace
- Date consistency
- Numerical values and their valid ranges
- Duplicate identifiers
- Logical consistency between related columns

The objective is not to modify valid data unnecessarily, but to ensure that the dataset is clean, consistent, and suitable for business analysis.

In [83]:
# Check columns names
df.columns = df.columns.str.strip() # Standardize
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country/Region',
 'City',
 'State/Province',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [84]:
# Check categorical values
categorical_columns = [
    "Ship Mode",
    "Segment",
    "Country/Region",
    "Region",
    "Category",
    "Sub-Category"
]

for col in categorical_columns:
    print(f"\n{col}:")
    print(df[col].unique())

print()
print(df[categorical_columns].nunique()) # Check the number of unique values

Ship Mode:
<StringArray>
['Standard Class', 'First Class', 'Second Class', 'Same Day']
Length: 4, dtype: str

Segment:
<StringArray>
['Consumer', 'Home Office', 'Corporate']
Length: 3, dtype: str

Country/Region:
<StringArray>
['United States', 'Canada']
Length: 2, dtype: str

Region:
<StringArray>
['Central', 'East', 'South', 'West']
Length: 4, dtype: str

Category:
<StringArray>
['Office Supplies', 'Furniture', 'Technology']
Length: 3, dtype: str

Sub-Category:
<StringArray>
[      'Paper',     'Binders',      'Labels',     'Storage',         'Art',
      'Chairs',   'Fasteners',      'Phones', 'Furnishings', 'Accessories',
   'Bookcases',   'Envelopes',  'Appliances',      'Tables',    'Supplies',
    'Machines',     'Copiers']
Length: 17, dtype: str

Ship Mode          4
Segment            3
Country/Region     2
Region             4
Category           3
Sub-Category      17
dtype: int64

In [85]:
# Check for unwanted whitespace
string_columns = df.select_dtypes(include="object").columns

for col in string_columns:
    whitespace_count = df[col].astype(str).str.strip().ne(df[col].astype(str)).sum()
    print(f"{col}: {whitespace_count} values with leading/trailing whitespace")

Order ID: 0 values with leading/trailing whitespace
Ship Mode: 0 values with leading/trailing whitespace
Customer ID: 0 values with leading/trailing whitespace
Customer Name: 0 values with leading/trailing whitespace
Segment: 0 values with leading/trailing whitespace
Country/Region: 0 values with leading/trailing whitespace
City: 0 values with leading/trailing whitespace
State/Province: 0 values with leading/trailing whitespace
Postal Code: 0 values with leading/trailing whitespace
Region: 0 values with leading/trailing whitespace
Product ID: 0 values with leading/trailing whitespace
Category: 0 values with leading/trailing whitespace
Sub-Category: 0 values with leading/trailing whitespace
Product Name: 0 values with leading/trailing whitespace

C:\Users\kashh\AppData\Local\Temp\ipykernel_5736\3415810220.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  string_columns = df.select_dtypes(include="object").columns

In [86]:
# Validate dates
print((df["Ship Date"] < df["Order Date"]).sum())

print("Order Date:", df["Order Date"].min(), "to", df["Order Date"].max())

print("Ship Date:", df["Ship Date"].min(), "to", df["Ship Date"].max())

0
Order Date: 2023-01-03 00:00:00 to 2026-12-30 00:00:00
Ship Date: 2023-01-07 00:00:00 to 2027-01-05 00:00:00

In [ ]:
# Validate numerical columns

# Quantity shouldn't be negative or zero for a normal sales transaction.
print((df["Quantity"] <= 0).sum())

# Sales should not be negative.
print((df["Sales"] < 0).sum())

# Discount should normally lie between 0 and 1 if represented as a proportion.
print(((df["Discount"] < 0) | (df["Discount"] > 1)).sum())

0
0
0

In [88]:
# Not a data-quality check, simply measuring how many loss-making transactions exist.
(df["Profit"] < 0).sum()

np.int64(1901)

In [89]:
# Validate the relationship between Sales, Quantity and Price
df[["Sales", "Quantity", "Discount", "Profit"]].describe()

              Sales      Quantity      Discount        Profit
count  10194.000000  10194.000000  10194.000000  10194.000000
mean     228.225854      3.791838      0.155385     28.673417
std      619.906839      2.228317      0.206249    232.465115
min        0.444000      1.000000      0.000000  -6599.978000
25%       17.220000      2.000000      0.000000      1.760800
50%       53.910000      3.000000      0.200000      8.690000
75%      209.500000      5.000000      0.200000     29.297925
max    22638.480000     14.000000      0.800000   8399.976000

In [91]:
# Recheck duplicates

# Order ID can legitimately occur multiple times because one order can contain multiple products.
df['Order ID'].duplicated().sum()

np.int64(5083)

In [92]:
print("Duplicate rows:", df.duplicated().sum())

print("Duplicate Order IDs:", df["Order ID"].duplicated().sum())

print("Duplicate Customer IDs:", df["Customer ID"].duplicated().sum())

print("Duplicate Product IDs:", df["Product ID"].duplicated().sum())

Duplicate rows: 0
Duplicate Order IDs: 5083
Duplicate Customer IDs: 9390
Duplicate Product IDs: 8332

### Data Cleaning & Preparation — Observations

The dataset was systematically checked for missing values, duplicate records, inconsistent categorical values, unwanted whitespace, invalid dates, and invalid numerical values.

- The dataset contains **10,194 records and 21 columns**.
- No missing values were found in any column.
- No completely duplicated rows were found.
- `Row ID` contains unique values for every record.
- Duplicate `Order ID`, `Customer ID`, and `Product ID` values were found, but these are **not data-quality errors**. The dataset is transaction-level, so the same order, customer, or product can legitimately appear across multiple records.
- All categorical columns contain consistent values with no unexpected categories:
  - `Ship Mode`: 4 categories
  - `Segment`: 3 categories
  - `Country/Region`: 2 categories
  - `Region`: 4 categories
  - `Category`: 3 categories
  - `Sub-Category`: 17 categories
- No leading or trailing whitespace was detected in the text-based columns.
- `Order Date` and `Ship Date` are stored as datetime values and contain valid dates.
- No record has a `Ship Date` earlier than its corresponding `Order Date`.
- `Quantity` contains no zero or negative values.
- `Sales` contains no negative values.
- `Discount` values are within the expected range of 0 to 1.
- `Postal Code` is stored as an object/string-like field. This is appropriate because postal codes are identifiers rather than numerical measurements and should not be treated as quantities.

Therefore, **no major data-cleaning transformations were required**. The dataset is structurally consistent and ready for exploratory data analysis.

The duplicate ID values will be retained because they represent valid relationships within transactional data rather than duplicate records.